basePath: /api/v1
definitions:
  serializer.LoginRequest:
    properties:
      name:
        type: string
      phone_no:
        type: string
      token:
        type: integer
    required:
    - phone_no
    - token
    type: object
  serializer.RegisterRequest:
    properties:
      phone_no:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - phone_no
    type: object
  serializer.SendPvMessage:
    properties:
      content:
        type: string
      room_id:
        type: integer
      sender:
        type: integer
      type:
        type: string
    required:
    - content
    - room_id
    type: object
  serializer.Token:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  utils.DummyMessage:
    properties:
      content:
        type: string
      room_id:
        type: integer
      type:
        type: string
    required:
    - content
    - room_id
    - type
    type: object
  utils.ErrorResponse:
    properties:
      detail:
        type: string
      error_code:
        type: integer
      status:
        type: boolean
    type: object
  utils.RegisterResponse:
    properties:
      detail:
        type: string
      isSignup:
        type: boolean
    type: object
externalDocs:
  description: OpenAPI
host: localhost:8080
info:
  contact:
    name: API Support
  description: This is a Gin chat documentation
  license:
    name: Apache 2.0
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/:
    post:
      consumes:
      - application/json
      description: 1 min for every request, not authenticated, and returns a JWT token
      parameters:
      - description: Register details
        in: body
        name: Register
        required: true
        schema:
          $ref: '#/definitions/serializer.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.RegisterResponse'
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.RegisterResponse'
        "400":
          description: Too_Many_Token_Request(7) | Token_Expired_Or_Invalid(2) | We_Don't_Know_What_Happened(8)
            | MUST_NOT_AUTHENTICATED(1)
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: send token
      tags:
      - Authenticate
    put:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT token
      parameters:
      - description: Login details
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/serializer.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Token'
        "400":
          description: Object_Not_Found(6) | Token_Expired_Or_Invalid(2) | Name_Field_Required_For_Register(12)
            | We_Don't_Know_What_Happened(8) | MUST_NOT_AUTHENTICATED(1)
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: check token
      tags:
      - Authenticate
  /chat/ws:
    post:
      consumes:
      - application/json
      description: |-
        Sends a chat message to a specific user or group
        type is either pv_message or group_message
      parameters:
      - description: Message body
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/utils.DummyMessage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.SendPvMessage'
        "500":
          description: Internal Server Error
      summary: connect to websocket and send message
      tags:
      - chat
securityDefinitions:
  Json Web Token (jwt):
    type: basic
swagger: "2.0"
